### ISSUE TITLE
Need warning about "preconfigured" network

### ISSUE THREAD

**Issue by jxmx** [AllStarLink/cockpit-wifimanager#2]
![image](https://github.com/user-attachments/assets/9adb9c3c-8fbc-4525-a234-72e140877b0a)

**Comment by Allan-N** [comment]
Rather than adding a warning, can we reach into the configuration to get the associated SSID?

or maybe we should have the list of configured networks show both the profile name and the associated SSID?

**Comment by Allan-N** [comment]
Actually, I think displaying both the profile name and SSID needs to happen.

Why?  A while back I used `nmtui` to create a second profile for my cell phone personal hotspot.  I now have 2 profiles on my system and neither is displayed correctly/informatively.  The first profile, "preconfigured", should as noted above show the SSID.  The second profile, "Personal Hotspot", should also show the SSID.

<img width="392" alt="2-wifi-profiles" src="https://github.com/user-attachments/assets/d0091d96-b464-4ebe-adcf-f3a51adc26d6">
